# fly.toml app configuration file generated for reactivities-bashjb on 2023-12-20T12:44:53-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reactivities-bashjb"
primary_region = "ord"

[build]
  image = "bashjb/reactivities:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dtstg3dc5"
  Cloudinary__ApiKey="478182323772833"